version: '3'

services:
  api:
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    volumes:
      - ./server:/src
      - /src/node_modules
    environment:
      DOCKER_COMMAND: 'npm run start:debug'
      DB_HOST: mongo
      DB_PORT: 27017
      PORT: 3001
    env_file: server/.env
    ports:
      - 3001:3001
      - 56745:56745
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  web:
    build:
      context: ./client
      dockerfile: docker/Dockerfile
    command: 'npm run start'
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file: client/.env
    ports:
      - 3000:3000
